apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsserver
spec:
  selector:
    matchLabels:
      app: jsserver
  template:
    metadata:
      labels:
        app: jsserver
    spec:
      containers:
      - name: jsserver
        image: jsserver
        ports:
        - containerPort: 3000