apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: jsserver
  newName: raelmartins44/gitopsjs
  newTag: 36d625cde7706631c9141cfccf94bc7c6230a28e
